server:
  port: 8081
  servlet:
    session:
      cookie:
        domain: localhost
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: auth
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 991911
