server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.SQL: trace
    org.springframework.transaction.interceptor: trace
